# Generated by Django 6.0.7 on 2026-07-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('consultorio', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='medicos.especialidad')),
            ],
        ),
    ]
