# Generated by Django 6.0.7 on 2026-07-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_medicos/')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('sintomas', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='citas.cita')),
            ],
        ),
    ]
