# Generated by Django 6.0.7 on 2026-07-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='archivomedico',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='historias.historialmedico'),
        ),
    ]
